In [52]:
import numpy as np
import random
import pysindy as ps
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
pd.options.mode.chained_assignment = None

In [55]:
df = pd.read_csv("tables/blue.csv")

In [65]:
df.set_index(["num_trains", "name"])

                  t1    t2    t3    t4    t5    t6    t7    t8    t9
num_trains name
20         s_1   1.0   8.0   6.0  14.0   6.0  14.0   6.0  14.0   7.0
           x_1   7.0   6.0   6.0  -0.0  -0.0  -0.0  -0.0  -0.0  -0.0
           r_1   0.0  -0.0   8.0   6.0  14.0   6.0  14.0   6.0  13.0
40         s_1   1.0   8.0  12.0  28.0  11.0  28.0  16.0  38.0  39.0
           x_1   7.0  12.0  20.0  -0.0  -0.0  -0.0  -0.0  -0.0  -0.0
           r_1   0.0  -0.0   8.0  12.0  28.0  11.0  24.0   2.0   1.0
60         s_1   1.0   7.0  13.0  21.0  11.0  38.0  49.0  58.0  59.0
           x_1   7.0  11.0  39.0   0.0   2.0   0.0   0.0   0.0   0.0
           r_1   0.0   1.0   0.0  13.0  21.0  11.0  11.0   2.0   1.0
80         s_1   1.0   3.0   6.0  25.0  11.0  39.0  56.0  66.0  67.0
           x_1   7.0  13.0  38.0  13.0  -0.0  -0.0  -0.0  -0.0  -0.0
           r_1   0.0  -0.0  -0.0   1.0  25.0  11.0   5.0   2.0   1.0

$$
\begin{tabular}{llrrrrrrrrr}
 &  & t1 & t2 & t3 & t4 & t5 & t6 & t7 & t8 & t9 \\
num_trains & name &  &  &  &  &  &  &  &  &  \\
\multirow[c]{3}{*}{20} & s_1 & 1.000000 & 8.000000 & 6.000000 & 14.000000 & 6.000000 & 14.000000 & 6.000000 & 14.000000 & 7.000000 \\
 & x_1 & 7.000000 & 6.000000 & 6.000000 & -0.000000 & -0.000000 & -0.000000 & -0.000000 & -0.000000 & -0.000000 \\
 & r_1 & 0.000000 & -0.000000 & 8.000000 & 6.000000 & 14.000000 & 6.000000 & 14.000000 & 6.000000 & 13.000000 \\
\multirow[c]{3}{*}{40} & s_1 & 1.000000 & 8.000000 & 12.000000 & 28.000000 & 11.000000 & 28.000000 & 16.000000 & 38.000000 & 39.000000 \\
 & x_1 & 7.000000 & 12.000000 & 20.000000 & -0.000000 & -0.000000 & -0.000000 & -0.000000 & -0.000000 & -0.000000 \\
 & r_1 & 0.000000 & -0.000000 & 8.000000 & 12.000000 & 28.000000 & 11.000000 & 24.000000 & 2.000000 & 1.000000 \\
\multirow[c]{3}{*}{60} & s_1 & 1.000000 & 7.000000 & 13.000000 & 21.000000 & 11.000000 & 38.000000 & 49.000000 & 58.000000 & 59.000000 \\
 & x_1 & 7.000000 & 11.000000 & 39.000000 & 0.000000 & 2.000000 & 0.000000 & 0.000000 & 0.000000 & 0.000000 \\
 & r_1 & 0.000000 & 1.000000 & 0.000000 & 13.000000 & 21.000000 & 11.000000 & 11.000000 & 2.000000 & 1.000000 \\
\multirow[c]{3}{*}{80} & s_1 & 1.000000 & 3.000000 & 6.000000 & 25.000000 & 11.000000 & 39.000000 & 56.000000 & 66.000000 & 67.000000 \\
 & x_1 & 7.000000 & 13.000000 & 38.000000 & 13.000000 & -0.000000 & -0.000000 & -0.000000 & -0.000000 & -0.000000 \\
 & r_1 & 0.000000 & -0.000000 & -0.000000 & 1.000000 & 25.000000 & 11.000000 & 5.000000 & 2.000000 & 1.000000 \\
\end{tabular}$$